""" Discord Gateway intents that limit incoming events.

When identifying to a gateway, you can specify `intents` which allow you to
conditionally subscribe to pre-defined groups of events.

If you do not specify a certain intent, you will not receive any of the gateway
events that are batched into that group.

NOTE: Any events not defined in an intent are "passthrough," and will always be
      sent.
NOTE: GUILD_MEMBER_UPDATE is always sent for the current user, regardless of the
      GUILD_MEMBERS intent.
"""

DIRECT_MESSAGE_REACTIONS = 1 << 13
# MESSAGE_REACTION_ADD
# MESSAGE_REACTION_REMOVE
# MESSAGE_REACTION_REMOVE_ALL
# MESSAGE_REACTION_REMOVE_EMOJI

DIRECT_MESSAGE_TYPING = 1 << 14
# TYPING_START

DIRECT_MESSAGES = 1 << 12
# CHANNEL_PINS_UPDATE
# MESSAGE_CREATE
# MESSAGE_DELETE
# MESSAGE_UPDATE

GUILD_BANS = 1 << 2
# GUILD_BAN_ADD
# GUILD_BAN_REMOVE

GUILD_EMOJIS = 1 << 3
# GUILD_EMOJIS_UPDATE

GUILD_INTEGRATIONS = 1 << 4
# GUILD_INTEGRATIONS_UPDATE

GUILD_INVITES = 1 << 6
# INVITE_CREATE
# INVITE_DELETE

GUILD_MESSAGE_REACTIONS = 1 << 10
# MESSAGE_REACTION_ADD
# MESSAGE_REACTION_REMOVE
# MESSAGE_REACTION_REMOVE_ALL
# MESSAGE_REACTION_REMOVE_EMOJI

GUILD_MESSAGE_TYPING = 1 << 11
# TYPING_START

GUILD_MESSAGES = 1 << 9
# MESSAGE_CREATE
# MESSAGE_DELETE
# MESSAGE_DELETE_BULK
# MESSAGE_UPDATE

GUILD_VOICE_STATES = 1 << 7
# VOICE_STATE_UPDATE

GUILD_WEBHOOKS = 1 << 5
# WEBHOOKS_UPDATE

GUILDS = 1 << 0
# CHANNEL_CREATE
# CHANNEL_DELETE
# CHANNEL_UPDATE
# CHANNEL_PINS_UPDATE
# GUILD_CREATE
# GUILD_DELETE
# GUILD_UPDATE
# GUILD_ROLE_CREATE
# GUILD_ROLE_DELETE
# GUILD_ROLE_UPDATE

# PRIVILEGED INTENTS
# The application must have the below intents enabled in the Developer Portal.

GUILD_MEMBERS = 1 << 1
# GUILD_MEMBER_ADD
# GUILD_MEMBER_REMOVE
# GUILD_MEMBER_UPDATE

GUILD_PRESENCES = 1 << 8
# PRESENCE_UPDATE
